version: '2'
services:
  test-app:
    build: .
    command: bundle exec middleman build --build-dir=public/ --clean --verbose
    volumes:
      - './:/app'
    working_dir: /app
    environment:
      BASE_PATH: "/guides/fraud-prevention/"